### PR TITLE
[FIVE-162 improvement]

### PR DESCRIPTION
**Pull request by martinmena**
- Creado método único para establecer opciones y mostrar snackbar en ProjectsList.
- Los componentes hijos ahora usan ese método solo, en lugar de uno para establecer las opciones, y otro para mostrarlo.

### CODE REVIEW

**Comment by matiasbeckerle** [comment]
What happened with this one? It's OK if you have to close PRs (it happens) but have in mind to leave a comment explaining what's the reasoning behind it. It serves to help anyone searching for something and for tracking purposes.

**Comment by martinmena** [comment]
This PR was closed because, for some reason, even tho I cheked 3 or 4 time that the merge was from FIVE-162 Improvements into FIVE-162, when GitHub created it, it was into the wrong branch (master). The PR was immediately closed, and a new and correct one was created (from FIVE-162 Improvement into FIVE-162)

**Comment by matiasbeckerle** [comment]
Thanks! If you mean the target base branch (not sure if that's what you were dealing with) you can update it. Sometimes I make that mistake and then I proceed to edit the PR.

**Comment by martinmena** [comment]
> Thanks! If you mean the target base branch (not sure if that's what you were dealing with) you can update it. Sometimes I make that mistake and then I proceed to edit the PR.

Ohh, didn't know that, I'll keep it in mind for next time. I always thought I had to create a new one

**Pull request closed without merging**
